# Note:  This is an example config, see habitat_baselines/config/pointnav/ppo_pointnav.yaml
# for better hyperparameters for actual trainingrgb

BASE_TASK_CONFIG_PATH: "configs/tasks/objectnav_mp3d_il.yaml"
TRAINER_NAME: "ddp-objectnav-bc-env"
ENV_NAME: NavRLEnv
SIMULATOR_GPU_ID: 0
TORCH_GPU_ID: 0
VIDEO_OPTION: []
TENSORBOARD_DIR: "tb/objectnav/overfitting_ssl/rgb/seed_2_obs_transform/"
VIDEO_DIR: "video_dir/objectnav/overfitting_ssl/rgb/seed_2_obs_transform/"
# To evaluate on all episodes, set this to -1
TEST_EPISODE_COUNT: -1
EVAL_CKPT_PATH_DIR: "data/new_checkpoints/objectnav_ssl/objectnav_mp3d_40k/rgb_best/seed_1/best_rgb_objectnav_ckpt_31.pth"
SHOW_TOP_DOWN_MAP: False
NUM_PROCESSES: 11
CHECKPOINT_FOLDER: "data/new_checkpoints/objectnav/overfitting_ssl/rgb/seed_2_obs_transform/"
OUTPUT_LOG_DIR: data/objectnav/logs
LOG_INTERVAL: 10
LOG_METRICS: True
NUM_CHECKPOINTS: -1
NUM_ENVS: 11
CHECKPOINT_INTERVAL: 100
SENSORS: ['RGB_SENSOR']
DATASET_PATH: "/srv/flash1/rramrakhya6/habitat-lab/data/datasets/objectnav_mp3d_v2/{split}/{scene_split}.db"
RESULTS_DIR: "data/objectnav/results/overfitting_ssl/rgb/{split}/{type}"
INTERRUPTED_STATE_FILE: "data/new_checkpoints/objectnav/overfitting_ssl/semseg/seed_2_obs_transform/interrupted_state.pth"
EVAL_RESUTLS_DIR: "data/objectnav/results/"
EVAL_SAVE_RESULTS: True
EVAL_SAVE_RESULTS_INTERVAL: 50
EVAL:
  SPLIT: "val_mini"
  USE_CKPT_CONFIG: False
  sample: False
  semantic_metrics: False
  evaluation_meta_file: "data/meta_data/temp.json"
NUM_UPDATES: 16000
SAVE_FRAMES: False

IL:
  USE_IW: True
  distrib_backend: NCCL
  BehaviorCloning:
    lr: 0.001
    eps: 1.0e-5
    clip_param: 0.2
    num_mini_batch: 1
    max_grad_norm: 0.2
    num_steps: 128
    use_linear_clip_decay: False
    use_linear_lr_decay: True
    reward_window_size: 50
    sync_frac: 0.6
  OBS_AUGMENTATIONS: "color_jitter-translate_v2"
  OBS_AUGMENTATIONS_PARAMS:
    COLOR_JITTER:
      brightness: 0.4
      contrast: 0.4
      saturation: 0.4
      hue: 0.4
      color_p: 1.0
    TRANSLATE:
      pad: 16
      crop_size: 256
  OBS_TRANSFORMS:
    ENABLED_TRANSFORMS: ("ResizeShortestEdge", "CenterCropper")

RL:
  SUCCESS_REWARD: 2.5
  SLACK_REWARD: -1e-3

MODEL:
  ablate_depth: False
  ablate_rgb: False
  num_recurrent_layers: 2
  rnn_type: "GRU"
  backbone: "resnet18"
  resnet_baseplanes: 32
  normalize_visual_inputs: True
  force_blind_policy: False
  embed_sge: True
  embed_goal_seg: False
  sem_seg_pred: False
  NO_VISION: False
  USE_SEMANTICS: False
  USE_PRED_SEMANTICS: False
  SWITCH_TO_PRED_SEMANTICS_UPDATE: 0
  SEMANTIC_ENCODER:
    rednet_ckpt: "data/rednet-models/rednet_semmap_mp3d_40_v2_vince.pth"
    cnn_type: "ResnetSemSeqEncoder"
    output_size: 256
    backbone: "resnet18"
    train_encoder: True
    embedding_size: 4
    is_thda: True
    num_classes: 29
  RGB_ENCODER:
    cnn_type: "ResnetRGBEncoder"
    output_size: 256
    backbone: "resnet50_gn"
    train_encoder: True
    pretrained_ckpt: "data/models/omnidata_DINO_02.pth"
  DEPTH_ENCODER:
    cnn_type: "None"
    output_size: 128
    backbone: "resnet50"
    trainable: False
    ddppo_checkpoint: "data/ddppo-models/gibson-2plus-resnet50.pth"
  STATE_ENCODER:
    hidden_size: 2048
    rnn_type: "GRU"
    num_recurrent_layers: 2
  SEQ2SEQ:
    use_prev_action: True
  PROGRESS_MONITOR:
    use: False
