# Note:  This is an example config, see habitat_baselines/config/pointnav/ppo_pointnav.yaml
# for better hyperparameters for actual trainingsemseg

BASE_TASK_CONFIG_PATH: "configs/tasks/objectnav_mp3d_il.yaml"
TRAINER_NAME: "ddp-objectnav-bc-env"
ENV_NAME: NavRLEnv
SIMULATOR_GPU_ID: 0
TORCH_GPU_ID: 0
VIDEO_OPTION: ["disk"]
TENSORBOARD_DIR: "tb/objectnav/objectnav_ssl/objectnav_mp3d_40k/semseg/seed_1_best/"
VIDEO_DIR: "video_dir/objectnav/objectnav_ssl/objectnav_mp3d_40k/semseg/seed_1_best/"
# To evaluate on all episodes, set this to -1
TEST_EPISODE_COUNT: -1
EVAL_CKPT_PATH_DIR: "data/new_checkpoints/objectnav_ssl/objectnav_mp3d_40k/semseg_best/seed_1/best_semseg_objectnav_ckpt.pth"
SHOW_TOP_DOWN_MAP: False
NUM_PROCESSES: 1
CHECKPOINT_FOLDER: "data/new_checkpoints/objectnav/objectnav_ssl/semseg/seed_1_best/"
OUTPUT_LOG_DIR: data/objectnav/logs
LOG_INTERVAL: 10
LOG_METRICS: True
NUM_CHECKPOINTS: -1
CHECKPOINT_INTERVAL: 500
SENSORS: ['RGB_SENSOR', 'SEMANTIC_SENSOR', 'DEPTH_SENSOR']
DATASET_PATH: "/srv/flash1/rramrakhya6/habitat-lab/data/datasets/objectnav_mp3d_v2/{split}/{scene_split}.db"
RESULTS_DIR: "data/objectnav/results/objectnav_ssl/semseg/{split}/{type}"
INTERRUPTED_STATE_FILE: "data/new_checkpoints/objectnav/objectnav_ssl/semseg/seed_1_best/interrupted_state.pth"
EVAL_RESUTLS_DIR: "data/objectnav/results/"
EVAL_SAVE_RESULTS: True
EVAL_SAVE_RESULTS_INTERVAL: 50
EVAL:
  SPLIT: "val_mini"
  USE_CKPT_CONFIG: False
  sample: False
  semantic_metrics: False
  evaluation_meta_file: "tb/objectnav/objectnav_ssl/semseg/seed_1_best/evaluation_meta_35k_3.json"
NUM_UPDATES: 20000

IL:
  USE_IW: True
  distrib_backend: NCCL
  BehaviorCloning:
    lr: 0.001
    eps: 1.0e-5
    clip_param: 0.2
    num_mini_batch: 2
    max_grad_norm: 0.2
    num_steps: 32
    use_linear_clip_decay: False
    use_linear_lr_decay: True
    reward_window_size: 50
    sync_frac: 0.6
  OBS_AUGMENTATIONS: "color_jitter-translate_v2"
  OBS_TRANSFORMS:
    ENABLED_TRANSFORMS: ("ResizeShortestEdge", "CenterCropper")



RL:
  SUCCESS_REWARD: 2.5
  SLACK_REWARD: -1e-3

MODEL:
  ablate_depth: False
  ablate_semseg: False
  num_recurrent_layers: 2
  rnn_type: "GRU"
  backbone: "resnet18"
  resnet_baseplanes: 32
  normalize_visual_inputs: True
  force_blind_policy: False
  embed_sge: True
  embed_goal_seg: False
  semseg: False
  NO_VISION: False
  USE_SEMANTICS: True
  USE_PRED_SEMANTICS: True
  SWITCH_TO_PRED_SEMANTICS_UPDATE: 0
  SEMANTIC_ENCODER:
    rednet_ckpt: "data/rednet-models/rednet_semmap_mp3d_40_v2_vince.pth"
    cnn_type: "ResnetSemSeqEncoder"
    output_size: 256
    backbone: "resnet18"
    train_encoder: True
    embedding_size: 4
    is_thda: True
    num_classes: 29
  RGB_ENCODER:
    cnn_type: "ResnetRGBEncoder"
    output_size: 256
    backbone: "resnet50_gn"
    train_encoder: True
    pretrained_ckpt: "data/new_checkpoints/rgb_encoders/omnidata_DINO_02.pth"
  DEPTH_ENCODER:
    cnn_type: "VlnResnetDepthEncoder"
    output_size: 128
    backbone: "resnet50"
    trainable: False
    ddppo_checkpoint: "data/ddppo-models/gibson-2plus-resnet50.pth"
  STATE_ENCODER:
    hidden_size: 2048
    rnn_type: "GRU"
    num_recurrent_layers: 2
  SEQ2SEQ:
    use_prev_action: True
  PROGRESS_MONITOR:
    use: False
